apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argo-rollout-stg
  namespace: argocd
spec:
  project: default
  source:
    repoURL: git@github.com:ZinhTruong/devops_lab.git
    targetRevision: main
    path: argo-rollout/overlays/stg
  destination:
    server: https://kubernetes.default.svc
    namespace: staging
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
