apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: instavote
  namespace: argocd
  labels:
    team: instavote
spec:
  description: Production AppProject for the instavote rollout.

  sourceRepos:
  - https://github.com/ZinhTruong/devops_lab.git
  - git@github.com:ZinhTruong/devops_lab.git

  destinations:
  - namespace: prod
    server: https://kubernetes.default.svc

  clusterResourceWhitelist:
  - group: "*"
    kind: "*"

  namespaceResourceWhitelist:
  - group: "*"
    kind: "*"
