apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kite-app-dev
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/ZinhTruong/devops_lab
    targetRevision: main
    path: projects/kite-app/overlays/dev
  destination:
    server: https://kubernetes.default.svc
    namespace: training
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
