apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: instavote-prod
  namespace: argocd
spec:
  project: instavote
  source:
    repoURL: https://github.com/ZinhTruong/devops_lab.git
    targetRevision: main
    path: argo-rollout/overlays/prod
  destination:
    server: https://kubernetes.default.svc
    namespace: prod
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true