apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: instavote
  namespace: argocd
spec:
  sourceRepos:
  - https://github.com/ZinhTruong/devops_lab

  destinations:
  - namespace: stg
    server: https://kubernetes.default.svc
  - namespace: prod
    server: https://kubernetes.default.svc

  clusterResourceWhitelist:
  - group: "*"
    kind: "*"

  namespaceResourceWhitelist:
  - group: "*"
    kind: "*"